In [4]:
!pip install numpy

In [5]:
import numpy as np
import pandas as pd

In [6]:
# To create a simple numpy array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
# Two dimantion 
arr = np.array([[0,1,2],[3,4,5]])
print(arr)

[[0 1 2]
 [3 4 5]]


In [8]:
arr.shape

(2, 3)

In [9]:
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6


In [10]:
a = np.array([1,2,3])
b= np.array([4,5,6])
print(a+b)
print(b+a)
print(a-b)

[5 7 9]
[5 7 9]
[-3 -3 -3]


In [ ]:
# In silicing the - mean that what the last

In [11]:
# Random numbers between 0 and 1
print(np.random.rand())

0.16513795452394486


In [13]:
# Random numbers between 0 and 100
print(np.random.rand()*100)

62.97601584738823


In [12]:
# Generate an array of Random numbers 
print(np.random.rand(2,2))

[[0.42565277 0.88090422]
 [0.59560215 0.99660155]]
